project:
  type: website

website:
  page-navigation: true
  back-to-top-navigation: true
  title: "U.S. Greenhouse Gas Center Documentation"
  site-url: "https://us-ghg-center.github.io/ghgc-docs"
  repo-url: https://github.com/us-ghg-center/ghgc-docs
  repo-actions: [edit, issue]

  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; CC-By US GHG Center, 2022-2023"

  sidebar:
    logo: "logo/ghgc-logo-light.svg"
    pinned: true
    align: center
    tools:
      # - icon: info-circle
      #   href: https://www.earthdata.nasa.gov/esds/veda
      #   text: "earthdata.nasa.gov/esds/veda"
      - icon: globe-americas
        href: https://earth.gov/ghgcenter
        text: "US GHG Center Website"
      - icon: github
        href: https://github.com/us-ghg-center/ghgc-docs
        text: "Repository home"

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Welcome
      - section: User Services
        contents:
          - services/apis.qmd
          - services/jupyterhub.qmd
      # - href: datausage.qmd
      #   text: Data Usage Notebooks   
      # - href: datatransformation.qmd
      #   text: Data Transformation Documentation 
      # - href: processingreport.qmd
      #   text: Processing and Verification Reports   
      # - href: workflow.qmd
      #   text: Data Workflow
      # - href: advanceduser.qmd
      #   text: Advanced User Notebooks
      - section: datausage.qmd
        text: Data Usage Notebooks
        contents:
          - section: Gridded Anthropogenic Greenhouse Gas Emissions
            contents:
              - user_data_notebooks/oco2-mip-co2budget-yeargrid-v1_User_Notebook.ipynb
              - user_data_notebooks/odiac-ffco2-monthgrid-v2023_User_Notebook.ipynb
              - user_data_notebooks/ct-ch4-monthgrid-v2023_User_Notebook.ipynb
              - user_data_notebooks/epa-ch4emission-grid-v2express_User_Notebook.ipynb
              - user_data_notebooks/vulcan-ffco2-yeargrid-v4_User_Notebook.ipynb
              - user_data_notebooks/gra2pes-ghg-monthgrid-v1_User_Notebook.ipynb
          - section: Natural Greenhouse Gas Sources Emissions and Sinks
            contents:
              - user_data_notebooks/eccodarwin-co2flux-monthgrid-v5_User_Notebook.ipynb
              - user_data_notebooks/micasa-carbonflux-daygrid-v1_User_Notebook.ipynb
              - user_data_notebooks/gosat-based-ch4budget-yeargrid-v1_User_Notebook.ipynb
              - user_data_notebooks/oco2-mip-co2budget-yeargrid-v1_User_Notebook.ipynb
              - user_data_notebooks/ct-ch4-monthgrid-v2023_User_Notebook.ipynb
              - user_data_notebooks/lpjeosim-wetlandch4-grid-v1_User_Notebook.ipynb
          - section: Large Emissions Events
            contents:
              - user_data_notebooks/emit-ch4plume-v1_User_Notebook.ipynb
              - user_data_notebooks/goes-ch4plume-v1_User_Notebook.ipynb              
          - section: Greenhouse Gas Concentrations
            contents:
              - user_data_notebooks/noaa-insitu_User_Notebook.ipynb
              - user_data_notebooks/oco2geos-co2-daygrid-v10r_User_Notebook.ipynb
              - user_data_notebooks/influx-testbed-ghg-concentrations_User_Notebook.ipynb
              - user_data_notebooks/lam-testbed-ghg-concentrations_User_Notebook.ipynb
              - user_data_notebooks/nec-testbed-ghg-concentrations_User_Notebook.ipynb
          - section: Socioeconomic
            contents:
              - user_data_notebooks/sedac-popdensity-yeargrid5yr-v4.11_User_Notebook.ipynb
      - href: utility.qmd
        text: Utility Functions                                       
      - section: datatransformationcode.qmd
        text: Data Transformation Notebooks
        contents:
          - section: Gridded Anthropogenic Greenhouse Gas Emissions
            contents:
              - cog_transformation/oco2-mip-co2budget-yeargrid-v1.ipynb
              - cog_transformation/odiac-ffco2-monthgrid-v2023.ipynb
              - cog_transformation/ct-ch4-monthgrid-v2023.ipynb
              - cog_transformation/epa-ch4emission-grid-v2express.ipynb   
              - cog_transformation/vulcan-ffco2-yeargrid-v4.ipynb
              - cog_transformation/gra2pes-ghg-monthgrid-v1.ipynb
          - section: Natural Greenhouse Gas Sources Emissions and Sinks
            contents:
              - cog_transformation/eccodarwin-co2flux-monthgrid-v5.ipynb
              - cog_transformation/gosat-based-ch4budget-yeargrid-v1.ipynb
              - cog_transformation/oco2-mip-co2budget-yeargrid-v1.ipynb
              - cog_transformation/ct-ch4-monthgrid-v2023.ipynb
          - section: Large Emissions Events
            contents:
              - cog_transformation/emit-ch4plume-v1.ipynb
              - cog_transformation/goes-ch4plume-v1.ipynb
              
          - section: Greenhouse Gas Concentrations
            contents:
              - cog_transformation/noaa-gggrn-concentrations.ipynb
              - cog_transformation/oco2geos-co2-daygrid-v10r.ipynb
              - cog_transformation/influx-testbed-ghg-concentrations.ipynb
              - cog_transformation/lam-testbed-ghg-concentrations.ipynb
              - cog_transformation/nec-testbed-ghg-concentrations.ipynb
              
          - section: Socioeconomic
            contents:
              - cog_transformation/sedac-popdensity-yeargrid5yr-v4.11.ipynb
      - section: processingreport.qmd
        text: Processing and Verification Reports
        contents:
          - section: Gridded Anthropogenic Greenhouse Gas Emissions
            contents:
              - processing_and_verification_reports/oco2-mip-co2budget-yeargrid-v1_Processing and Verification Report.qmd
              - processing_and_verification_reports/odiac-ffco2-monthgrid-v2023_Processing and Verification Report.qmd
              - processing_and_verification_reports/ct-ch4-monthgrid-v2023_Processing and Verification Report.qmd
              - processing_and_verification_reports/epa-ch4emission-grid-v2express_Processing and Verification Report.qmd 
              - processing_and_verification_reports/vulcan-ffco2-yeargrid-v4_Processing and Verification Report.qmd  

          - section: Natural Greenhouse Gas Sources Emissions and Sinks
            contents:
              - processing_and_verification_reports/eccodarwin-co2flux-monthgrid-v5_Processing and Verification Report.qmd
              - processing_and_verification_reports/micasa-carbonflux-daygrid-v1_Processing and Verification Report.qmd
              - processing_and_verification_reports/gosat-based-ch4budget-yeargrid-v1_Processing and Verification Report.qmd
              - processing_and_verification_reports/oco2-mip-co2budget-yeargrid-v1_Processing and Verification Report.qmd
              - processing_and_verification_reports/ct-ch4-monthgrid-v2023_Processing and Verification Report.qmd
              - processing_and_verification_reports/lpjeosim-wetlandch4-grid-v1_Processing and Verification Report.qmd
          - section: Large Emissions Events
            contents:
              - processing_and_verification_reports/emit-ch4plume-v1_Processing and Verification Report.qmd
              - processing_and_verification_reports/goes-ch4plume-v1_Processing and Verification Report.qmd
          - section: Greenhouse Gas Concentrations
            contents:
              - processing_and_verification_reports/noaa-gggrn-co2-concentrations_Processing and Verification Report.qmd
              - processing_and_verification_reports/noaa-gggrn-ch4-concentrations_Processing and Verification Report.qmd
              - processing_and_verification_reports/oco2geos-co2-daygrid-v10r_Processing and Verification Report.qmd
              - processing_and_verification_reports/influx-testbed-ghg-concentrations_Processing and Verification Report.qmd
              - processing_and_verification_reports/lam-testbed-ghg-concentrations_Processing and Verification Report.qmd
              - processing_and_verification_reports/nec-testbed-ghg-concentrations_Processing and Verification Report.qmd           
          - section: Socioeconomic
            contents:
              - processing_and_verification_reports/sedac-popdensity-yeargrid5yr-v4.11_Processing and Verification Report.qmd
      - section: workflow.qmd
        text: Data Flow Diagrams
        contents:
          - section: Gridded Anthropogenic Greenhouse Gas Emissions
            contents:
              - data_workflow/oco2-mip-co2budget-yeargrid-v1_Data_Flow.qmd
              - data_workflow/odiac-ffco2-monthgrid-v2023_Data_Flow.qmd
              - data_workflow/ct-ch4-monthgrid-v2023_Data_Flow.qmd
              - data_workflow/epa-ch4emission-grid-v2express_Data_Flow.qmd
              - data_workflow/vulcan-ffco2-yeargrid-v4_Data_Flow.qmd  
              - data_workflow/gra2pes-ghg-monthgrid-v1_Data_Flow.qmd 

          - section: Natural Greenhouse Gas Sources Emissions and Sinks
            contents:
              - data_workflow/eccodarwin-co2flux-monthgrid-v5_Data_Flow.qmd
              - data_workflow/micasa-carbonflux-daygrid-v1_Data_Flow.qmd
              - data_workflow/gosat-based-ch4budget-yeargrid-v1_Data_Flow.qmd
              - data_workflow/oco2-mip-co2budget-yeargrid-v1_Data_Flow.qmd
              - data_workflow/ct-ch4-monthgrid-v2023_Data_Flow.qmd
              - data_workflow/lpjeosim-wetlandch4-grid-v1_Data_Flow.qmd
          - section: Large Emissions Events
            contents:
              - data_workflow/emit-ch4plume-v1_Data_Flow.qmd
              - data_workflow/goes-ch4plume-v1_Data_Flow.qmd              
          - section: Greenhouse Gas Concentrations
            contents:
              - data_workflow/noaa-gggrn-co2-concentrations_Data_Flow.qmd
              - data_workflow/noaa-gggrn-ch4-concentrations_Data_Flow.qmd
              - data_workflow/oco2geos-co2-daygrid-v10r_Data_Flow.qmd
              - data_workflow/influx-testbed-ghg-concentrations_Data_Flow.qmd
              - data_workflow/lam-testbed-ghg-concentrations_Data_Flow.qmd
              - data_workflow/nec-testbed-ghg-concentrations_Data_Flow.qmd
          - section: Socioeconomic
            contents:
              - data_workflow/sedac-popdensity-yeargrid5yr-v4.11_Data_Flow.qmd
  
format:
  html:
    grid:
      sidebar-width: 25vw
      body-width: 900px
    theme:
      light: [flatly]
      dark: [darkly]
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true
    toc-depth: 3
filters:
  - quarto
