---
title: "U.S. Greenhouse Gas Center: Advanced User Notebook"
---

Welcome to the [U.S. Greenhouse Gas (GHG) Center: Advanced User Notebook](https://earth.gov/ghgcenter), your gateway to exploring and analyzing curated datasets on greenhouse gas emissions.
Our cloud-based system offers seamless access to Greenhouse Gas curated datasets. Dive into the data with our data usage Jupyter notebooks, designed for efficient exploration, visualization, and analysis.
Whether you are focused on specific focus areas or product types, our dataset usage notebooks provide invaluable insights to drive informed decision-making.

Join us in our mission to make data-driven environmental solutions.
Explore, analyze, and make a difference with the U.S. GHG Center.

## Gridded Anthropogenic Greenhouse Gas Emissions
1. [OCO-2 MIP Top-Down National CO₂ Budgets](user_data_notebooks/oco2-mip-National-co2budget) - Model Output

## Natural Greenhouse Gas Sources Emissions and Sinks

## Large Emissions Events

## Greenhouse Gas Concentrations

## Socioeconomic

## Contact

For technical help or general questions, please contact the support team using the [feedback form](https://docs.google.com/forms/d/e/1FAIpQLSeVWCrnca08Gt_qoWYjTo6gnj1BEGL4NCUC9VEiQnXA02gzVQ/viewform).