---
title: "U.S. Greenhouse Gas Center: Data Transformation Documentation"
---

The [U.S. Greenhouse Gas (GHG) Center](https://earth.gov/ghgcenter) provides a cloud-based system for exploring and analyzing U.S. government and other curated greenhouse gas datasets.

You can find the jupyter notebooks for each dataset explaining how each dataset has been transformed from orifinal file to COGs.
Dataset **transformation** examples:

## Gridded Anthropogenic Greenhouse Gas Emissions
1. [OCO-2 MIP Top-Down CO₂ Budgets](cog_transformation/oco2-mip-co2budget-yeargrid-v1.ipynb) - Model Output
2. [ODIAC Fossil Fuel CO₂ Emissions](cog_transformation/odiac-ffco2-monthgrid-v2022.ipynb) - Model Output
3. [TM5-4DVar Isotopic CH₄ Inverse Fluxes](cog_transformation/tm54dvar-ch4flux-monthgrid-v1.ipynb) - Model Output,Ground Measurements
4. [U.S. Gridded Anthropogenic Methane Emissions Inventory](cog_transformation/epa-ch4emission-grid-v2express.ipynb) - Gridded Inventory

## Natural Greenhouse Gas Sources Emissions and Sinks
1. [Air-Sea CO₂ Flux, ECCO-Darwin Model v5](cog_transformation/eccodarwin-co2flux-monthgrid-v5.ipynb) - Model Output
2. [CASA-GFED3 Land Carbon Flux](cog_transformation/casagfed-carbonflux-monthgrid-v3.ipynb) - Model Output
3. [GOSAT-based Top-down Total and Natural Methane Emissions](cog_transformation/gosat-based-ch4budget-yeargrid-v1.ipynb) - Model Output
4. [OCO-2 MIP Top-Down CO₂ Budgets](cog_transformation/oco2-mip-co2budget-yeargrid-v1.ipynb) - Model Output
5. [TM5-4DVar Isotopic CH₄ Inverse Fluxes](cog_transformation/tm54dvar-ch4flux-monthgrid-v1.ipynb) - Model Output,Ground Measurements
6. [Monthly Wetland Methane Emissions from the LPJ-wsl model](cog_transformation/lpjwsl-wetlandch4-monthgrid-v1.ipynb) - Model Output

## Large Emissions Events
1. [EMIT Methane Point Source Plume Complexes](cog_transformation/emit-ch4plume-v1.ipynb) - Satellite Observations

##
1. [OCO-2 GEOS Column CO₂ Concentrations](cog_transformation/oco2geos-co2-daygrid-v10r.ipynb) - Model Output, - Satellite Observations

## Socioeconomic
1. [SEDAC Gridded World Population Density](cog_transformation/sedac-popdensity-yeargrid5yr-v4.11.ipynb) - Model Output

## Contact

For technical help or general questions, please contact the support team using the [feedback form](https://docs.google.com/forms/d/e/1FAIpQLSeVWCrnca08Gt_qoWYjTo6gnj1BEGL4NCUC9VEiQnXA02gzVQ/viewform).