---
title: "U.S. Greenhouse Gas Center: Data Usage Notebooks"
---

Welcome to the homepage for the [U.S. Greenhouse Gas (GHG) Center](https://earth.gov/ghgcenter) data usage notebooks. Each dataset available in the [GHG Center Data Catalog](https://earth.gov/ghgcenter/data-catalog) has an associated “Introductory notebook” created by the GHG Center team which demonstrates how to access, visualize, and conduct basic data analysis in a Jupyter Notebook environment. Additional notebooks may be provided with each dataset. Click on a dataset under “GHG Center Dataset Tutorials” to learn more about the dataset and to view the associated code notebooks.

Along with GHG Center-curated notebooks, science users can also contribute notebooks that use GHG Center datasets. Notebooks submitted by the scientific community can be found under the “Community-Contributed Tutorials” section. 

## GHG Center Dataset Tutorials
Tutorial notebooks created by the GHG Center team. Introductory notebooks demonstrate how to access, visualize, and conduct basic data analysis for each dataset available in the [GHG Center Data Catalog](https://earth.gov/ghgcenter/data-catalog). Notebooks demonstrating how to conduct additional or more specialized analyses may also be listed under the relevant dataset.

- Black Marble Nighttime at Sensor Radiance
   - [Introductory notebook](user_data_notebooks/blackmarble-radiance-daygrid-v2nrt_User_Notebook.ipynb )<br><br>

- BlueFlux CO₂ and CH₄ Fluxes for Southern Florida Wetlands
   - [Introductory notebook](user_data_notebooks/blueflux-ghgflux-daygrid-v1_User_Notebook.ipynb)<br><br>

- CarbonTracker-CH₄ Isotopic CH₄ Flux Estimates
   - [Introductory notebook](user_data_notebooks/ct-ch4-monthgrid-v2023_User_Notebook.ipynb)<br><br>

- ECCO-Darwin Modeled CO₂-Ocean Flux
   - [Introductory notebook](user_data_notebooks/eccodarwin-co2flux-monthgrid-v5_User_Notebook.ipynb)<br><br>

- EMIT CH₄ Point Source Plume Complexes
   - [Introductory notebook](user_data_notebooks/emit-ch4plume-v1_User_Notebook.ipynb)<br><br>

- Global Ecosystem Dynamics Investigation (GEDI) Aboveground Biomass Density
   - [Introductory notebook](user_data_notebooks/gedi-agb-grid-v2.1_User_Notebook.ipynb)<br><br>

- Global Mangrove Aboveground Biomass and Canopy Height
   - [Introductory notebook](user_data_notebooks/cms-mangrove-agb-canopyheight-grid-v1.3_User_Notebook.ipynb)<br><br>

- Goddard Earth Observing System (GEOS) Assimilated CO₂, CH₄, and CO Column Concentrations
   - [Introductory notebook](user_data_notebooks/geos-ghg-daygrid-vPRE_User_Notebook.ipynb)<br><br>

- GOES Geostationary Satellite CH₄ Emission Observations
   - [Introductory notebook](user_data_notebooks/goes-ch4plume-v1_User_Notebook.ipynb)<br><br>

- GOSAT-based Total and Wetland CH₄ Emissions
   - [Introductory notebook](user_data_notebooks/gosat-based-ch4budget-yeargrid-v1_User_Notebook.ipynb)<br><br>

- GRA²PES Greenhouse Gas and Air Quality Species
   - [Introductory notebook](user_data_notebooks/gra2pes-ghg-monthgrid-v1_User_Notebook.ipynb)<br><br>

- Indianapolis Flux Experiment CO₂ and CH₄ Concentrations
   - [Introductory notebook](user_data_notebooks/influx-testbed-ghg-concentrations_User_Notebook)<br><br>

- Los Angeles Megacity Carbon Project CO₂ and CH₄ Concentrations
   - [Introductory notebook](user_data_notebooks/lam-testbed-ghg-concentrations_User_Notebook)<br><br>

- LPJ-EOSIM Global Simulated Wetland CH₄ Emissions
   - [Introductory notebook](user_data_notebooks/lpjeosim-wetlandch4-grid-v1_User_Notebook.ipynb)<br><br>

- MiCASA Land Carbon Flux
   - [Introductory notebook](user_data_notebooks/micasa-carbonflux-daygrid-v1_User_Notebook.ipynb)<br><br>

- NOAA Global Monitoring Laboratory Atmospheric CO₂ Concentrations
   - [Introductory notebook](user_data_notebooks/noaa-insitu_User_Notebook.ipynb)<br><br>

- Northeast Corridor Urban Test Bed CO₂ and CH₄ Concentrations
   - [Introductory notebook](user_data_notebooks/nec-testbed-ghg-concentrations_User_Notebook)<br><br>

- OCO-2 Goddard Earth Observing System (GEOS) CO₂ Column Concentrations
   - [Introductory notebook](user_data_notebooks/oco2geos-co2-daygrid-v10r_User_Notebook.ipynb)<br><br>

- OCO-2 Modeling Intercomparison Project (MIP) CO₂ Flux
   - [Introductory notebook](user_data_notebooks/oco2-mip-co2budget-yeargrid-v1_User_Notebook.ipynb) 
   - [Intermediate level notebook](user_data_notebooks/oco2-mip-National-co2budget.ipynb) to read and visualize National CO₂ Budgets using OCO-2 MIP Top-Down CO₂ Budget country total data. This notebook utilizes the country totals available at [https://ceos.org/gst/carbon-dioxide.html](https://ceos.org/gst/carbon-dioxide.html), which compliment the global 1° x 1° gridded CO₂ Budget data featured in the [US GHG Center](https://earth.gov/ghgcenter/data-catalog/oco2-mip-co2budget-yeargrid-v1).<br><br>

- OCO-3 Snapshot Area Maps of Column CO₂ Concentrations
   - [Introductory notebook](user_data_notebooks/oco3-co2-sams-daygrid-v11r_User_Notebook.ipynb)<br><br>

- ODIAC Fossil Fuel CO₂ Emissions
   - [Introductory notebook](user_data_notebooks/odiac-ffco2-monthgrid-v2024_User_Notebook.ipynb)<br><br>

- SEDAC Gridded World Population Density
   - [Introductory notebook](user_data_notebooks/sedac-popdensity-yeargrid5yr-v4.11_User_Notebook.ipynb)<br><br>

- U.S. Gridded Anthropogenic CH₄ Emissions Inventory
   - [Introductory notebook](user_data_notebooks/epa-ch4emission-grid-v2express_User_Notebook.ipynb)<br><br>

- Vulcan Fossil Fuel CO₂ Emissions
   - [Introductory notebook](user_data_notebooks/vulcan-ffco2-yeargrid-v4_User_Notebook.ipynb)<br><br>


## Community-Contributed Tutorials
Notebooks provided by the scientific community that use GHG Center datasets. The GHG Center is in the process of establishing a workflow for community notebook contribution. Once available, the contribution process will be published here. In the meantime, please submit any notebook contribution inquiries through the [US GHG Center Contact Form](https://docs.google.com/forms/d/e/1FAIpQLSeVWCrnca08Gt_qoWYjTo6gnj1BEGL4NCUC9VEiQnXA02gzVQ/viewform).    
**Note**: these notebooks are contributed by the scientific community, and are not actively maintained by the GHG Center team.

## Contact

For technical help or general questions, please contact the support team using the [feedback form](https://docs.google.com/forms/d/e/1FAIpQLSeVWCrnca08Gt_qoWYjTo6gnj1BEGL4NCUC9VEiQnXA02gzVQ/viewform).