---
title: "U.S. Greenhouse Gas Center: Data Transformation Notebooks"
---

Welcome to the [U.S. Greenhouse Gas (GHG) Center](https://earth.gov/ghgcenter) data transformation notebooks, where we harness the power of Cloud Optimized Geotiffs (COGs) to offer a dynamic, cloud-based platform for exploring and analyzing greenhouse gas datasets.
Dive into our curated collection of GHG datasets, all optimized for seamless accessibility and analysis. 

Discover the journey of each dataset from its original format to COGs through the below Jupyter notebooks. The transformation examples are grouped topically. The dataset product type (model output, satellite observation, etc.) is noted next to the notebook name. Click on a notebook to learn more about the dataset and to view the transformation code.

Join us in our mission to make data-driven environmental solutions.
Explore, analyze, and make a difference with the US GHG Center.

**Note**: Not all datasets have a transformation code

[View the US GHG Center Data Catalog](https://earth.gov/ghgcenter/data-catalog)

## Gridded Anthropogenic Greenhouse Gas Emissions
1. [OCO-2 MIP Top-Down CO₂ Budgets](cog_transformation/oco2-mip-co2budget-yeargrid-v1.ipynb)
2. [ODIAC Fossil Fuel CO₂ Emissions](cog_transformation/odiac-ffco2-monthgrid-v2023.ipynb)
3. [CarbonTracker-CH₄ Isotopic Methane Inverse Fluxes](cog_transformation/ct-ch4-monthgrid-v2023.ipynb)
4. [U.S. Gridded Anthropogenic Methane Emissions Inventory](cog_transformation/epa-ch4emission-grid-v2express.ipynb)
5. [Vulcan Fossil Fuel CO₂ Emissions](cog_transformation/vulcan-ffco2-yeargrid-v4.ipynb)
6. [GRA²PES Greenhouse Gas and Air Quality Species](cog_transformation/gra2pes-ghg-monthgrid-v1.ipynb)

## Natural Greenhouse Gas Emissions and Sinks
1. [Air-Sea CO₂ Flux, ECCO-Darwin Model v5](cog_transformation/eccodarwin-co2flux-monthgrid-v5.ipynb)
2. [GOSAT-based Top-down Total and Natural Methane Emissions](cog_transformation/gosat-based-ch4budget-yeargrid-v1.ipynb)
3. [OCO-2 MIP Top-Down CO₂ Budgets](cog_transformation/oco2-mip-co2budget-yeargrid-v1.ipynb)
4. [CarbonTracker-CH₄ Isotopic Methane Inverse Fluxes](cog_transformation/ct-ch4-monthgrid-v2023.ipynb)


## Large Emissions Events
1. [EMIT Methane Point Source Plume Complexes](cog_transformation/emit-ch4plume-v1.ipynb)
2. [Geostationary Satellite Observations of Extreme and Transient Methane Emissions from Oil and Gas Infrastructure](cog_transformation/goes-ch4plume-v1.ipynb)

## Greenhouse Gas Concentrations
1. [Atmospheric Carbon Dioxide and Methane Concentrations from NOAA Global Monitoring Laboratory](cog_transformation/noaa-gggrn-concentrations.ipynb)
2. [OCO-2 GEOS Column CO₂ Concentrations](cog_transformation/oco2geos-co2-daygrid-v10r.ipynb)
3. [Carbon Dioxide and Methane Concentrations from the Indianapolis Flux Experiment (INFLUX)](cog_transformation/influx-testbed-ghg-concentrations.ipynb)
4. [Carbon Dioxide and Methane Concentrations from the Los Angeles Megacity Carbon Project](cog_transformation/lam-testbed-ghg-concentrations.ipynb)
5. [Carbon Dioxide and Methane Concentrations from the Northeast Corridor (NEC) Urban Test Bed](cog_transformation/nec-testbed-ghg-concentrations.ipynb)

## Socioeconomic
1. [SEDAC Gridded World Population Density](cog_transformation/sedac-popdensity-yeargrid5yr-v4.11.ipynb)

## Contact

For technical help or general questions, please contact the support team using the [feedback form](https://docs.google.com/forms/d/e/1FAIpQLSeVWCrnca08Gt_qoWYjTo6gnj1BEGL4NCUC9VEiQnXA02gzVQ/viewform).