---
title: "Introduction to U.S. Greenhouse Gas Center: Data Usage Notebooks"
subtitle: "Resource for Exploratory Analysis for the US GHG Center"
---

## Welcome {#welcome}

The [U.S. Greenhouse Gas (GHG) Center](https://earth.gov/ghgcenter) provides a cloud-based system for exploring and analyzing U.S. government and other curated greenhouse gas datasets.

On this site, you can find the technical documentation for the services the center provides, how to load the datasets, and how the datasets were transformed from their source formats (eg. netCDF, HDF, etc.) into cloud-optimized formats that enable efficient cloud data access and visualization.


## Contents

1. Dataset **usage** examples listed below.

## Explore Data Usage Notebook

1. [CASA-GFED3 Land Carbon Flux](user_data_notebooks/casagfed-carbonflux-monthgrid-v3_User_Notebook.ipynb)
2. [Air-Sea CO₂ Flux, ECCO-Darwin Model v5](user_data_notebooks/eccodarwin-co2flux-monthgrid-v5_User_Notebook.ipynb) 
3. [EMIT Methane Point Source Plume Complexes](user_data_notebooks/emit-ch4plume-v1_User_Notebook.ipynb) 
4. [U.S. Gridded Anthropogenic Methane Emissions Inventory](user_data_notebooks/epa-ch4emission-grid-v2express_User_Notebook.ipynb) 
5. [GOSAT-based Top-down Total and Natural Methane Emissions](user_data_notebooks/gosat-based-ch4budget-yeargrid-v1_User_Notebook.ipynb) 
6. [Wetland Methane Emissions, LPJ-wsl Model](user_data_notebooks/lpjwsl-wetlandch4-grid-v1_User_Notebook.ipynb) 
          
7. [OCO-2 MIP Top-Down CO₂ Budgets](user_data_notebooks/oco2-mip-co2budget-yeargrid-v1_User_Notebook.ipynb)
8. [OCO-2 GEOS Column CO₂ Concentrations](user_data_notebooks/oco2geos-co2-daygrid-v10r_User_Notebook.ipynb)
9. [ODIAC Fossil Fuel CO₂ Emissions](user_data_notebooks/odiac-ffco2-monthgrid-v2022_User_Notebook.ipynb)
10. [SEDAC Gridded World Population Density](user_data_notebooks/sedac-popdensity-yeargrid5yr-v4.11_User_Notebook.ipynb)
11. [TM5-4DVar Isotopic CH₄ Inverse Fluxes](user_data_notebooks/tm54dvar-ch4flux-monthgrid-v1_User_Notebook.ipynb)
12. [Atmospheric Carbon Dioxide Concentrations from NOAA Global Monitoring Laboratory](user_data_notebooks/noaa-insitu_User_Notebook.ipynb)