---
title: "U.S. Greenhouse Gas Center: Documentation"
subtitle: "Resources for the US GHG Center"
---

## Welcome {#welcome}

The [U.S. Greenhouse Gas (GHG) Center](https://earth.gov/ghgcenter) provides a cloud-based system for exploring and analyzing U.S. government and other curated greenhouse gas datasets.

On this site, you can find the technical documentation for the services the center provides, how to load the datasets, and how the datasets were transformed from their source formats (eg. netCDF, HDF, etc.) into cloud-optimized formats that enable efficient cloud data access and visualization.


## Contents

1. **Services** provided for accessing and analyzing the US GHG Center datasets, such as the [JupyterHub](services/jupyterhub.qmd) environment for interactive computing.
2. Dataset **usage** examples, e.g. for the [Wetland Methane Emissions from the LPJ-EOSIM model](user_data_notebooks/lpjeosim-wetlandch4-grid-v2_User_Notebook.ipynb) dataset, that shows how to load the dataset in Python in [JupyterHub](services/jupyterhub.qmd).
3. Dataset **transformation** scripts, which document the code used to transform datasets for display in the US GHG Center. An example is the [ODIAC Fossil Fuel CO₂ Emissions](cog_transformation/odiac-ffco2-monthgrid-v2023.ipynb) dataset transformation code.
4. Data **processing and verification reports** that openly present the process we used to check and verify that any transformation did not alter the original source data. An example is the [GOSAT-based Top-down Total and Natural Methane Emissions](processing_and_verification_reports/gosat-based-ch4budget-yeargrid-v1_Processing and Verification Report.qmd) dataset.
5. Data **Flow Diagrams**, which provide a high level summary of how each dataset was integrated into the US GHG Center. See the [MiCASA Land Carbon Flux Flow Diagram](data_workflow/micasa-carbonflux-daygrid-v1_Data_Flow.qmd) as an example.

## Contact

For technical help or general questions, please contact the support team using the [feedback form](https://docs.google.com/forms/d/e/1FAIpQLSeVWCrnca08Gt_qoWYjTo6gnj1BEGL4NCUC9VEiQnXA02gzVQ/viewform).