---
title: "U.S. Greenhouse Gas Center: Processing and Verification Reports"
---

Welcome to the homepage for the [U.S. Greenhouse Gas (GHG) Center](https://earth.gov/ghgcenter) processing and verification reports. These reports document the steps taken to verify the accuracy and integrity of each dataset once it’s processed into the U.S. GHG Center.

Click on a dataset name to view the processing and verification report for that dataset.

Examples of processing that may occur include transforming data from its source format into a could-optimized format, converting the units of the source data into a more common or standard unit, and flagging "nodata" values to ensure accurate data visualization. We strive to responsibly handle all data, and share these reports to provide transparency and insight into any processing that is applied, while ensuring accuracy and reliability throughout the process.

[View the US GHG Center Data Catalog](https://earth.gov/ghgcenter/data-catalog)

- [Air-Sea CO₂ Flux, ECCO-Darwin Model v5 Processing and Verification Report](processing_and_verification_reports/eccodarwin-co2flux-monthgrid-v5_Processing and Verification Report.qmd)

- [Atmospheric Carbon Dioxide Concentrations from the NOAA Global Monitoring Laboratory Processing and Verification Report](processing_and_verification_reports/noaa-gggrn-co2-concentrations_Processing and Verification Report.qmd)

- [Atmospheric Methane Concentrations from the NOAA Global Monitoring Laboratory Processing and Verification Report](processing_and_verification_reports/noaa-gggrn-ch4-concentrations_Processing and Verification Report.qmd)

- [Carbon Dioxide and Methane Concentrations from the Indianapolis Flux Experiment (INFLUX) Processing and Verification Report](processing_and_verification_reports/influx-testbed-ghg-concentrations_Processing and Verification Report.qmd)

- [Carbon Dioxide and Methane Concentrations from the Los Angeles Megacity Carbon Project Processing and Verification Report](processing_and_verification_reports/lam-testbed-ghg-concentrations_Processing and Verification Report.qmd)

- [Carbon Dioxide and Methane Concentrations from the Northeast Corridor (NEC) Urban Test Bed Processing and Verification Report](processing_and_verification_reports/nec-testbed-ghg-concentrations_Processing and Verification Report.qmd)

- [CarbonTracker-CH₄ Isotopic Methane Inverse Fluxes Processing and Verification Report](processing_and_verification_reports/ct-ch4-monthgrid-v2023_Processing and Verification Report.qmd)

- [EMIT Methane Point Source Plume Complexes Processing and Verification Report](processing_and_verification_reports/emit-ch4plume-v1_Processing and Verification Report.qmd)

- [Geostationary Satellite Observations of Extreme and Transient Methane Emissions from Oil and Gas Infrastructure Processing and Verification Report](processing_and_verification_reports/goes-ch4plume-v1_Processing and Verification Report.qmd)

- [GOSAT-based Top-down Total and Natural Methane Emissions Processing and Verification Report](processing_and_verification_reports/gosat-based-ch4budget-yeargrid-v1_Processing and Verification Report.qmd)

- [GRA²PES Greenhouse Gas and Air Quality Species Processing and Verification Report](processing_and_verification_reports/gra2pes-ghg-monthgrid-v1_Processing and Verification Report.qmd)

- [MiCASA Land Carbon Flux Processing and Verification Report](processing_and_verification_reports/micasa-carbonflux-daygrid-v1_Processing and Verification Report.qmd)

- [OCO-2 GEOS Column CO₂ Concentrations Processing and Verification Report](processing_and_verification_reports/oco2geos-co2-daygrid-v10r_Processing and Verification Report.qmd)

- [OCO-2 MIP Top-Down CO₂ Budgets Processing and Verification Report](processing_and_verification_reports/oco2-mip-co2budget-yeargrid-v1_Processing and Verification Report.qmd)

- [ODIAC Fossil Fuel CO₂ Emissions Processing and Verification Report](processing_and_verification_reports/odiac-ffco2-monthgrid-v2023_Processing and Verification Report.qmd)

- [SEDAC Gridded World Population Density Processing and Verification Report](processing_and_verification_reports/sedac-popdensity-yeargrid5yr-v4.11_Processing and Verification Report.qmd)

- [U.S. Gridded Anthropogenic Methane Emissions Inventory Processing and Verification Report](processing_and_verification_reports/epa-ch4emission-grid-v2express_Processing and Verification Report.qmd)

- [Vulcan Fossil Fuel CO₂ Emissions Processing and Verification Report](processing_and_verification_reports/vulcan-ffco2-yeargrid-v4_Processing and Verification Report.qmd)

- [Wetland Methane Emissions, LPJ-EOSIM Model Processing and Verification Report](processing_and_verification_reports/lpjeosim-wetlandch4-grid-v1_Processing and Verification Report.qmd)


## Contact

For technical help or general questions, please contact the support team using the [feedback form](https://docs.google.com/forms/d/e/1FAIpQLSeVWCrnca08Gt_qoWYjTo6gnj1BEGL4NCUC9VEiQnXA02gzVQ/viewform).