---
title: "U.S. Greenhouse Gas Center: Data Flow Diagrams"
---

Welcome to the homepage for [U.S. Greenhouse Gas (GHG) Center](https://earth.gov/ghgcenter) data workflow diagrams. Use these diagrams to discover the journey of each dataset from acquisition to integration in the US GHG Center.

Data flow diagrams are grouped topically and labeled by dataset name. Click on a dataset name to view the data flow diagram for that dataset, which summarizes the process followed to bring the dataset into the US GHG Center.

Join us in our mission to make data-driven environmental solutions accessible.
Explore, analyze, and make a difference with the US GHG Center.

[View the US GHG Center Data Catalog](https://earth.gov/ghgcenter/data-catalog)

## Gridded Anthropogenic Greenhouse Gas Emissions
1. [OCO-2 MIP Top-Down CO₂ Budgets Data Flow Diagram](data_workflow/oco2-mip-co2budget-yeargrid-v1_Data_Flow.qmd)
2. [ODIAC Fossil Fuel CO₂ Emissions Data Flow Diagram](data_workflow/odiac-ffco2-monthgrid-v2023_Data_Flow.qmd)
3. [CarbonTracker-CH₄ Isotopic Methane Inverse Fluxes Data Flow Diagram](data_workflow/ct-ch4-monthgrid-v2023_Data_Flow.qmd)
4. [U.S. Gridded Anthropogenic Methane Emissions Inventory Data Flow Diagram](data_workflow/epa-ch4emission-grid-v2express_Data_Flow.qmd)
5. [Vulcan Fossil Fuel CO₂ Emissions Data Flow Diagram](data_workflow/vulcan-ffco2-yeargrid-v4_Data_Flow.qmd)
6. [GRA²PES Greenhouse Gas and Air Quality Species Data Flow Diagram](data_workflow/gra2pes-ghg-monthgrid-v1_Data_Flow.qmd)
6. [GRA²PES Greenhouse Gas and Air Quality Species Data Flow Diagram](data_workflow/gra2pes-ghg-monthgrid-v1_Data_Flow.qmd)


## Natural Greenhouse Gas Sources Emissions and Sinks
1. [Air-Sea CO₂ Flux, ECCO-Darwin Model v5 Data Flow Diagram](data_workflow/eccodarwin-co2flux-monthgrid-v5_Data_Flow.qmd)
2. [MiCASA Land Carbon Flux Data Flow Diagram](data_workflow/micasa-carbonflux-daygrid-v1_Data_Flow.qmd)
3. [GOSAT-based Top-down Total and Natural Methane Emissions Data Flow Diagram](data_workflow/gosat-based-ch4budget-yeargrid-v1_Data_Flow.qmd)
4. [OCO-2 MIP Top-Down CO₂ Budgets Data Flow Diagram](data_workflow/oco2-mip-co2budget-yeargrid-v1_Data_Flow.qmd)
5. [CarbonTracker-CH₄ Isotopic Methane Inverse Fluxes Data Flow Diagram](data_workflow/ct-ch4-monthgrid-v2023_Data_Flow.qmd)
6. [Wetland Methane Emissions, LPJ-EOSIM Model Data Flow Diagram](data_workflow/lpjeosim-wetlandch4-grid-v1_Data_Flow.qmd)

## Large Emissions Events
1. [EMIT Methane Point Source Plume Complexes Data Flow Diagram](data_workflow/emit-ch4plume-v1_Data_Flow.qmd)

## Greenhouse Gas Concentrations
1. [Atmospheric Carbon Dioxide Concentrations from NOAA Global Monitoring Laboratory Data Flow Diagram](data_workflow/noaa-gggrn-co2-concentrations_Data_Flow.qmd)
2. [Atmospheric Methane Concentrations from NOAA Global Monitoring Laboratory Data Flow Diagram](data_workflow/noaa-gggrn-ch4-concentrations_Data_Flow.qmd)
3. [OCO-2 GEOS Column CO₂ Concentrations Data Flow Diagram](data_workflow/oco2geos-co2-daygrid-v10r_Data_Flow.qmd)
4. [Carbon Dioxide and Methane Concentrations from the Indianapolis Flux Experiment (INFLUX) Data Flow Diagram](data_workflow/influx-testbed-ghg-concentrations_Data_Flow.qmd)
5. [Carbon Dioxide and Methane Concentrations from the Los Angeles Megacity Carbon Project Data Flow Diagram](data_workflow/lam-testbed-ghg-concentrations_Data_Flow.qmd)
6. [Carbon Dioxide and Methane Concentrations from the Northeast Corridor (NEC) Urban Test Bed Data Flow Diagram](data_workflow/nec-testbed-ghg-concentrations_Data_Flow.qmd)
4. [Carbon Dioxide and Methane Concentrations from the Indianapolis Flux Experiment (INFLUX) Data Flow Diagram](data_workflow/influx-testbed-ghg-concentrations_Data_Flow.qmd)
5. [Carbon Dioxide and Methane Concentrations from the Los Angeles Megacity Carbon Project Data Flow Diagram](data_workflow/lam-testbed-ghg-concentrations_Data_Flow.qmd)
6. [Carbon Dioxide and Methane Concentrations from the Northeast Corridor (NEC) Urban Test Bed Data Flow Diagram](data_workflow/nec-testbed-ghg-concentrations_Data_Flow.qmd)

## Socioeconomic
1. [SEDAC Gridded World Population Density Data Flow Diagram](data_workflow/sedac-popdensity-yeargrid5yr-v4.11_Data_Flow.qmd)

## Contact

For technical help or general questions, please contact the support team using the [feedback form](https://docs.google.com/forms/d/e/1FAIpQLSeVWCrnca08Gt_qoWYjTo6gnj1BEGL4NCUC9VEiQnXA02gzVQ/viewform).