---
title: JupyterHub
---

The US GHG Center promotes the use of JupyterHub environments for interactive data science. JupyterHub enables you to analyze massive archives of Earth science data in the cloud in an interactive environment that alleviates the complexities of managing compute resources (virtual machines, roles and permissions, etc).

Users affiliated with the US GHG Center can get access to a dedicated JupyterHub service, provided in collaboration with [2i2c](https://2i2c.org/): [hub.ghg.center](https://hub.ghg.center/). Please find instructions for requesting access below.

If you are a scientist affiliated with other NASA projects such as [VEDA](https://nasa-impact.github.io/veda-docs/), [EIS](https://eis.smce.nasa.gov/about.html), and [MAAP](https://ops.maap-project.org), you can also keep using the resources provided by these projects. Through the use of open-source technology, we make sure our services are interoperable and exchangeable.


## To Get US GHG Center JupyterHub access:

 The US GHG Center notebook environment is available to authorized users on an as-need basis. If you are a user affiliated with the US GHG Center, you can gain access by using our [Hub Access Request form](https://docs.google.com/forms/d/e/1FAIpQLSdai8otCdrVQzJgev8mjDhzKyCg7jcrB3UeTXNHoCiaMKrkaQ/viewform).

* Make sure you have a [GitHub Account](https://docs.github.com/en/get-started/signing-up-for-github/signing-up-for-a-new-github-account). Take note of your [GitHub username](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/remembering-your-github-username-or-email).
* Fill out the [request form](https://docs.google.com/forms/d/e/1FAIpQLSdai8otCdrVQzJgev8mjDhzKyCg7jcrB3UeTXNHoCiaMKrkaQ/viewform) and provide needed information.
* Watch your email for notification of authorization and the invite to join the [US GHG Center Hub Access GitHub Team](https://GitHub.com/orgs/US-GHG-Center/teams/ghgc-hub-access).

* Once you accept the invitation, you can go to [hub.ghg.center](https://hub.ghg.center/) and login using your GitHub credentials.


## To access User Notebooks

This site provides [Jupyter notebooks](../user_data_notebooks/casagfed-carbonflux-monthgrid-v3_User_Notebook.ipynb) showing how to load and analyze Earth data in the interactive cloud computing environment.

Further instructions are included in each notebook.

If you have any questions, please use the [feedback form](https://docs.google.com/forms/d/e/1FAIpQLSeVWCrnca08Gt_qoWYjTo6gnj1BEGL4NCUC9VEiQnXA02gzVQ/viewform) to contact the US GHG Center user support team.